export const tableDataSuccess = JSON.stringify({
    success: true,
    data: {
        currency: 'USD',
        items: [
            {
                id: 'bitcoin',
                title: 'Bitcoin',
                symbol: 'BTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11,
                group: [
                    {
                        id: 'bitcoin-1',
                        symbol: 'BTC',
                        buyPrice: 0,
                        quantity: 0,
                        buyFee: 0,
                        sellFee: 0,
                        wallet: '',
                        date: 0
                    },
                    {
                        id: 'bitcoin-2',
                        symbol: 'BTC',
                        buyPrice: '',
                        quantity: '',
                        buyFee: '',
                        sellFee: '',
                        wallet: '',
                        date: ''
                    }
                ]
            },
            {
                id: 'Ethereum',
                title: 'Ethereum',
                symbol: 'ETH',
                image: '',
                quantity: 11,
                value: 21,
                price_buy: 31,
                price_current: 41,
                currency_buy: '',
                change: 51,
                fee_buy: 61,
                fee_sell: 71,
                sold: 81,
                gain: 91,
                quota: 101,
                wallet: '',
                date: 111
            },
            {
                id: 'Litecoin1',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin2',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin3',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin4',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin5',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin6',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin7',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin8',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin9',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin10',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin11',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin12',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin13',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin14',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin15',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin16',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin17',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin18',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin19',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin20',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin21',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin22',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin23',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin24',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin25',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin26',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin27',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin28',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin29',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin30',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin31',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin32',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Litecoin33',
                title: 'Litecoin',
                symbol: 'LTC',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            },
            {
                id: 'Tether',
                title: 'Tether',
                symbol: 'USDT',
                image: '',
                quantity: 1,
                value: 2,
                price_buy: 3,
                price_current: 4,
                currency_buy: '',
                change: 5,
                fee_buy: 6,
                fee_sell: 7,
                sold: 8,
                gain: 9,
                quota: 10,
                wallet: '',
                date: 11
            }
        ]
    }
});

export const tableDataError = JSON.stringify({
    success: true,
    data: {
        text: 'Error'
    }
});
